INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Acre', 'AC', 12);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Alagoas', 'AL', 27);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Amazonas', 'AM', 13);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Amapá', 'AP', 16);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Bahia', 'BA', 29);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Ceará', 'CE', 23);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Distrito Federal', 'DF', 53);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Espírito Santo', 'ES', 32);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Goiás', 'GO', 52);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Maranhão', 'MA', 21);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Minas Gerais', 'MG', 31);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Mato Grosso do Sul', 'MS', 50);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Mato Grosso', 'MT', 51);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Pará', 'PA', 15);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Paraiba', 'PB', 25);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Pernambuco', 'PE', 26);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Piauí', 'PI', 22);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Paraná', 'PR', 41);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Rio de Janeiro', 'RJ', 33);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Rio Grande do Norte', 'RN', 24);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Rondônia', 'RO', 11);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Roraima', 'RR', 14);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Rio Grande do Sul', 'RS', 43);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Santa Catarina', 'SC', 42);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Sergipe', 'SE', 28);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'São Paulo', 'SP', 35);
INSERT INTO "public"."uf" (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), E'Tocantins', 'TO', 17);