INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Acr', 'AC', 12);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Alagoas', 'AL', 27);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Amazonas', 'AM', 13);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Amapá', 'AP', 16);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Bahia', 'BA', 29);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Ceará', 'C', 23);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Distrito Federal', 'DF', 53);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Espírito Santo', 'ES', 32);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Goiás', 'GO', 52);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Maranhão', 'MA', 21);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Minas Gerais', 'MG', 31);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Mato Grosso do Sul', 'MS', 50);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Mato Grosso', 'MT', 51);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Pará', 'PA', 15);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Paraiba', 'PB', 25);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Pernambuco', 'P', 26);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Piauí', 'PI', 22);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Paraná', 'PR', 41);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Rio de Janeiro', 'RJ', 33);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Rio Grande do Nort', 'RN', 24);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Rondônia', 'RO', 11);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Roraima', 'RR', 14);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Rio Grande do Sul', 'RS', 43);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Santa Catarina', 'SC', 42);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Sergip', 'S', 28);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'São Paulo', 'SP', 35);
INSERT INTO uf (id_uf, nome, sigla, codigo_ibge) VALUES (nextval('uf_id_seq'), 'Tocantins', 'TO', 17);